### PR TITLE
Add support to WebP caching

### PR DESCRIPTION
**Pull request by NiccoMlt**
Add support to WebP caching even in case of query string

See #462

### CODE REVIEW

**Comment by hamadodene** [comment]
@NiccoMlt  In my opinion, it makes sense to add a dynamic property to allow the user to potentially add other extensions as well.

**Comment by NiccoMlt** [comment]
added `cache.cachealways` @hamadodene

**Comment by NiccoMlt** [comment]
Fixed default as requested @hamadodene

**Comment by hamadodene** [comment]
@NiccoMlt I don't know if what I think makes sense. But if I set cache.cachealways I also overwrite the defaults, right?
Maybe it's better if by setting the property they are added to the default? What do you think?

**Comment by NiccoMlt** [comment]
Yes, it should
See https://github.com/diennea/carapaceproxy/blob/1b5d9864cad85f36dfdf1bfa276e3f6e375fafc2/carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java#L280-L281

**Comment by NiccoMlt** [comment]
Oh ok, I've read your comment only half-way.

I don't like the idea of not being able to disable the "always cached" behaviour if I want to.

I think it is better to configure the whole list.

**Comment by hamadodene** [comment]
Make sense...LGTM

**Review by hamadodene — APPROVED** [review]

**Pull request merged**
